# Generated by Django 5.0.6 on 2024-09-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="group_image",
            field=models.ImageField(blank=True, null=True, upload_to="group_images/"),
        ),
    ]
